[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "invoice-scanner-shared"
version = "0.1.0"
description = "Shared utilities and configurations for Invoice Scanner services"

[tool.setuptools]
packages = ["shared"]
